name: Python

on:
  push:
    branches:
    - '*'

jobs:
  check-python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pylint

    - name: Analysing the code with pylint
      run: pylint --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**")

    - name: Build package
      run: python -m build
